set_clock_groups -asynchronous -group clk_fpga_0 -group clk_fpga_1

#NEED TO FIX FOLLOWING CONSTRAINTS FOR PACMAN V2 - WITH PDTS INTERFACE
set_property PACKAGE_PIN W17 [get_ports {cdr_clk_clk_p[0]}]
set_property PACKAGE_PIN W16 [get_ports {cdr_data_clk_p[0]}]
set_property PACKAGE_PIN M15 [get_ports {MISO_0[7]}]
set_property PACKAGE_PIN N15 [get_ports {MISO_0[6]}]
set_property PACKAGE_PIN R15 [get_ports {MISO_0[5]}]
set_property PACKAGE_PIN R16 [get_ports {MISO_0[4]}]
set_property PACKAGE_PIN H15 [get_ports {MOSI_0[31]}]
set_property PACKAGE_PIN J17 [get_ports {MOSI_0[30]}]
set_property PACKAGE_PIN J21 [get_ports {MOSI_0[29]}]
set_property PACKAGE_PIN J22 [get_ports {MOSI_0[28]}]
set_property PACKAGE_PIN K16 [get_ports {MOSI_0[19]}]
set_property PACKAGE_PIN L16 [get_ports {MOSI_0[18]}]
set_property PACKAGE_PIN M17 [get_ports {MOSI_0[17]}]
set_property PACKAGE_PIN N17 [get_ports {MOSI_0[16]}]
set_property PACKAGE_PIN N18 [get_ports {MOSI_0[11]}]
set_property PACKAGE_PIN N22 [get_ports {MOSI_0[10]}]
set_property PACKAGE_PIN P16 [get_ports {MOSI_0[9]}]
set_property PACKAGE_PIN P22 [get_ports {MOSI_0[8]}]
set_property PACKAGE_PIN AA18 [get_ports cdr_lol]
set_property IOSTANDARD LVCMOS25 [get_ports cdr_lol]
set_property PACKAGE_PIN Y18 [get_ports cdr_los]
set_property IOSTANDARD LVCMOS25 [get_ports cdr_los]
set_property PACKAGE_PIN AB21 [get_ports sfp_los]
set_property IOSTANDARD LVCMOS25 [get_ports sfp_los]
